/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   cuba-file-field.html
 */

/// <reference path="../polymer/types/polymer.d.ts" />
/// <reference path="../cuba-app/cuba-app-aware-behavior.d.ts" />

interface CubaFileFieldElement extends Polymer.Element, CubaAppAwareBehavior {

  /**
   * Label to be shown on the upload button.
   */
  label: string|null|undefined;

  /**
   * File descriptor object.
   */
  fileDescriptor: object|null|undefined;

  /**
   * The array of files being processed, or already uploaded. Bound to the corresponding property of
   * `vaadin-upload`.
   * Currently only single file is supported.
   */
  files: any[]|null|undefined;
  _computeHeaders(): any;
  _handleUploadSuccess(event: any, data: any): void;
  _handleFdChange(): void;
  _handleFileRemove(): void;
  _handleLabelChange(): void;
  _handleFileClick(event: any): any;
}

interface HTMLElementTagNameMap {
  "cuba-file-field": CubaFileFieldElement;
}
